name: Rust

on:
  push:
    branches: [ "master" ]

env:
  USER_DOCS: https://github.com/Retropaint/skelform_user_docs
  DEV_DOCS: https://github.com/Retropaint/skelform_dev_docs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
          
      - name: Cache
        uses: Swatinem/rust-cache@v2
          
      - name: pull lfs files
        run: git lfs pull
        
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.6"
          
      - name: build binary
        run: cd release && python3 release.py
        
      - name: upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly Build
          draft: false
          prerelease: false
          files: |
            release/SkelForm*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true

      - name: Cache
        uses: Swatinem/rust-cache@v2
          
      - name: pull lfs files
        run: git lfs pull

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.6"

      - name: build windows binary
        shell: bash
        run: cd release && python release.py

      - name: upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly Build
          draft: false
          prerelease: false
          files: |
            release/skelform_windows*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
          
      - name: Cache
        uses: Swatinem/rust-cache@v2
          
      - name: pull lfs files
        run: git lfs pull
          
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.6"
          
      - name: build binary
        run: cd release && python3 release.py --ubuntudeps
        
      - name: upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly Build
          draft: false
          prerelease: false
          files: |
            release/skelform_linux*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
